services:
  redmine:
    build: .
    volumes:
      - ../redmine:/usr/src/redmine
      - ../plugins:/usr/src/redmine/plugins
      - bundle-data:/usr/local/bundle
    env_file:
      - ./.user.env
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: postgres:13.3
    env_file:
      - ./.dbpass.env
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  bundle-data:
  db-data:
