services:
  redmine:
    environment:
      CAPYBARA_SERVER_HOST: redmine
      CAPYBARA_SERVER_PORT: 3000
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
      RAILS_ENV: test
    depends_on:
      - chrome
  chrome:
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - ../redmine/tmp/downloads:/home/seluser/Downloads
    ports:
      - 4444:4444
      - 5900:5900
