services:
  redmine:
    hostname: redmine
    volumes:
      - ../redmine:/workspace
      - ../plugins:/workspace/plugins
      - bundle-data:/usr/local/bundle
      - ./.cache:/home/user/.cache
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      BINDING: 0.0.0.0
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
    ports:
      - 3000:3000
    build:
      context: .
      args:
        LOCAL_UID: ${LOCAL_UID}
  db:
    image: postgres:13.3
    hostname: postgres
    env_file:
      - ./.dbpass.env
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  bundle-data:
  db-data:
